In [130]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [131]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [132]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [133]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms) 
df # fill NA values

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [134]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [135]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [136]:
reg.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [137]:
reg.intercept_


221323.00186540396

In [138]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

Exercise

In [139]:
data = pd.read_csv('hiring.csv')

In [140]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [141]:
data.experience

0       NaN
1       NaN
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [142]:
data.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [143]:
data.columns = ['experience','test_score','interview_score','salary']

In [144]:
data.columns


Index(['experience', 'test_score', 'interview_score', 'salary'], dtype='object')

In [145]:
data.test_score

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     NaN
7     7.0
Name: test_score, dtype: float64

In [146]:
median_test = math.floor(data.test_score.median())
median_test


8

In [147]:
data.test_score = data.test_score.fillna(median_test)
data

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [148]:
data= data.fillna('zero')
data

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [149]:
!pip install word2number




Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [150]:
import word2number #convert word to number
from word2number import w2n
#w2n.word_to_num('zero')

In [151]:
data.experience = data.experience.apply(w2n.word_to_num)


In [152]:
data

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [156]:
reg = linear_model.LinearRegression()
reg.fit(data[['experience','test_score','interview_score']], data.salary)

LinearRegression()

In [157]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [158]:
reg.intercept_

17737.263464337688

In [159]:
reg.predict([[2,10,10]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([63872.63464338])